### ISSUE TITLE
Ability to change scene and camera

### ISSUE THREAD

**Issue by robertlong** [pmndrs/postprocessing#410] opened 2022-09-15 06:10 UTC
### Is your feature request related to a problem?

In my project the `Scene` and `PerspectiveCamera` or `OrthographicCamera` instances change when you transition between environments. Currently there isn't a great way to swap the scene and camera for the various passes/effects at runtime.

### Describe the solution you'd like

I'd like there to be a standard `setScene(scene)` and `setCamera(camera)` API on the `EffectComposer` where each pass and effect will also have a corresponding `setScene` and `setCamera` API that is called when the method is called on the `EffectComposer`. Each effect can update anything associated with the scene or camera in its local state.

### Describe alternatives you've considered

I've tried to manually set the scene and camera on each of the effects but it involved some nasty hacks and fighting with typechecking.

I also could try to stick to only using a single scene and camera for the entire lifecycle of my app, but I'd really like the ability to swap them out at runtime.

I could also tear down the entire postprocessing stack and recreate it with the new scene/camera but that seems like an awful lot of wasted work for something that should be relatively inexpensive.

**Comment by vanruesc** [comment] 2022-09-20 21:38
Yes, postprocessing should provide an easy way to swap out the main scene and camera, but its current architecture is not well suited for that. I don't think it would be a good idea to add additional scene/camera API to effects and passes because most of them shouldn't require access to the main scene and camera in the first place.

For the next major release I'm planning to add a `GeometryPass` that will solely be responsible for managing the main scene and camera. A render pipeline will have at most one main `GeometryPass` whose camera settings will automatically be propagated to all other passes and effects in the same pipeline. There's more to it though which I'll explain in a discussion ticket soon.

Closing this as a duplicate of #391.

**Closed by vanruesc** 2022-09-20 21:38 UTC
Labels: feature request

**Comment by vanruesc** [comment] 2022-10-17 12:18
Added `EffectComposer.setMainScene()` and `EffectComposer.setMainCamera()` in `postprocessing@6.29.0`.
