### ISSUE TITLE
Black square artifacts when using bloom

### ISSUE THREAD

**Issue by 0xroko** [pmndrs/postprocessing#547] opened 2023-11-14 18:27 UTC
### Description of the bug

Using bloom effect causes artifacts (only at specific camera position). Artifact are more prevalent when using complex geometry (especially smooth normals)

### To Reproduce

https://codesandbox.io/s/diamond-refraction-bug-lsmfs8 
move around, artifacts will appear at certain position

### Screenshots

![image](https://github.com/pmndrs/postprocessing/assets/55251261/5d0b5f36-d637-4437-a0aa-dd4e27e8e764)

Artifact size is proportional to bloom levels
![image](https://github.com/pmndrs/postprocessing/assets/55251261/17fa9fed-03c1-4600-b79e-cc0ab7a04d29)

### Library versions used

 - Three: 0.158.0
 - Post Processing: 6.33.3

### Desktop

 - OS: 6.5.9-arch2-1 GNU/Linux
 - Browser Firefox 119.0 and 118.0.5993.117 (Official Build, ungoogled-chromium) Arch Linux (64-bit) 
 - Graphics hardware: NVIDIA-SMI 535.113.01  (gtx 1050)

**Comment by vanruesc** [comment] 2023-11-14 20:11
Looks like a duplicate of #526.

Please make sure that the model you're using isn't broken. Incorrect textures can cause lighting calculations to produce negative values.

**Comment by 0xroko** [comment] 2023-11-14 20:46
> Please make sure that the model you're using isn't broken

Not sure what constitutes as broken model (all models I tried have artifacts). Maybe it's the mix of MeshRefractionMaterial and Bloom pass?  But I just tested reproduction sandbox on Intel Macbook and I don't see any artifacts.

**Comment by 0xroko** [comment] 2023-11-15 10:56
Ok, the issue is division by 0.0 somewhere in `MeshRefractionMaterial`'s frag shader. I tested it by adding following at the end of `MeshRefractionMaterial`'s frag shader:
```glsl
  if(uv.x < 0.54 && uv.x > 0.5 && uv.y < 0.5 && uv.y > 0.46) {
    gl_FragColor = vec4(1.0 / 0.);
   }
```
And fixed artifact appears
![image](https://github.com/pmndrs/postprocessing/assets/55251261/3ec19634-3be7-4752-b95e-90b6cfaed27c)

**Comment by vanruesc** [comment] 2023-11-20 22:55
Closing this since it's not a bug in `postprocessing`.

**Closed by vanruesc** 2023-11-20 22:55 UTC
