### ISSUE TITLE
OverrideMaterialManager doesn't respect the original material's clippingPlanes

### ISSUE THREAD

**Issue by STINGNAILS** [pmndrs/postprocessing#397] opened 2022-08-05 13:54 UTC
### Description of the bug

Render passes ignore clipping planes, which results in visual artifacts for effects like SSAO

### To Reproduce

Sandbox example: https://codesandbox.io/s/jolly-keller-f9ji3p

### Expected behavior

I'd expect clipping planes from original materials to be copied to overriding materials (which probably means, a new one should be created for all the relevant objects; I realize this is quite bad for performance, but not sure if there is another approach that would work in general...)

### Screenshots

![image](https://user-images.githubusercontent.com/10925209/183091481-8bf32409-a2fd-415e-81c8-3c3959a47e1c.png)

**Comment by vanruesc** [comment] 2022-08-07 12:14
Duplicate of #319.

Please check if there are similar issues before opening new ones.

**Closed by vanruesc** 2022-08-07 12:14 UTC
