### ISSUE TITLE
Antialiasing has no effect when ClearColor is transparent

### ISSUE THREAD

**Issue by MrMateo7** [pmndrs/postprocessing#387] opened 2022-07-25 23:00 UTC
### Description of the bug

I've tried with both (SMAA and FXAA), but any looks correct effect when the renderer ClearColor is transparent.

### To Reproduce

`renderer.setClearColor(0xffffff, 0)`
...
```
const fxaaEffect = new FXAAEffect()
fxaaEffect.subpixelQuality = 0.1
```
...
```
const smaaEffect = new SMAAEffect()
smaaEffect.preset = SMAAPreset.ULTRA
smaaEffect.edgeDetectionMode = EdgeDetectionMode.COLOR
```

### Expected behavior

Antialiasing have the same effect when ClearColor have non-transparent value.

### Screenshots

No-transparent ClearColor.
![image](https://user-images.githubusercontent.com/80969412/180888290-ec1d49a0-fc2f-4414-a87c-51cb3c4780bf.png)

Transparent ClearColor.
![image](https://user-images.githubusercontent.com/80969412/180888559-67100c11-4eda-4354-9950-6b1e479de589.png)

NOW, if I use lower values in alpha at clearColor the thing gets better.
`renderer.setClearColor(0xffffff, 0.1)`

![image](https://user-images.githubusercontent.com/80969412/180889301-42f09000-580b-4084-9bae-7119f3e456fd.png)

But the background is annoying for the application that I needed.

### Library versions used

 - Three:  "^0.132.2"
 - Post Processing: "^6.28.4",

### Desktop

 - OS: [e.g. Windows]
 - Browser [e.g. Chrome X.X.X.X]
 - Graphics hardware: [e.g. NVIDIA]

### Mobile

 - Device: [e.g. iPhone]
 - OS: [e.g. Android]
 - Browser [e.g. Firefox X.X.X]

**Comment by vanruesc** [comment] 2022-07-26 22:45
Repro: https://codesandbox.io/s/affectionate-johnson-0lu79i?file=/src/App.js
The problem is that the edge detection logic in FXAA and SMAA ignores the alpha channel. I'm not sure yet how this should be handled.. maybe multiplying the color samples with the respective alpha values could work. I'll look into it.

**Comment by vanruesc** [comment] 2022-08-02 22:26
Unfortunately, I was unable to get FXAA/SMAA to work with a transparent canvas. Anti-aliasing works by blending pixels with neighboring pixels, but when the canvas is transparent, the AA won't have access to the pixels that are "behind" the canvas. The result is an incomplete AA-blend that doesn't remove the jaggies.

I tried using MSAA with a transparent canvas as well, and found that it has the same problem:

<img src="https://user-images.githubusercontent.com/9214917/182479555-09353140-5e92-484f-8776-a11ae4dfc381.png" width="300">

**Comment by vanruesc** [comment] 2022-08-14 20:49
Closing this as I don't think this can be solved. Feel free to reopen/comment if you or someone else knows a solution.

**Closed by vanruesc** 2022-08-14 20:49 UTC
Labels: enhancement
