### ISSUE TITLE
BloomEffect not working as expected

### ISSUE THREAD

**Issue by Makio64** [pmndrs/postprocessing#622] opened 2024-04-05 06:26 UTC
### Description of the bug

Adding the bloom with radius / intensity / treshold at 0 dont work

### To reproduce

here my minimal setup 

```
    renderer = new WebGLRenderer({
      powerPreference: 'high-performance',
      alpha: false,
      antialias: false,
      depth: false,
      stencil: false,
      logarithmicDepthBuffer: false
    })
    renderer.toneMapping = NoToneMapping

    this.composer = new EffectComposer(renderer, {
      frameBufferType: HalfFloatType
    })
    this.composer.addPass(new RenderPass(scene, camera))

    this.bloom = new BloomEffect({}) // also tried passing the arguments here
    this.bloom.intensity = 0
    this.bloom.luminanceMaterial.threshold = 0
    this.bloom.luminanceMaterial.smoothing = 0.001
    this.composer.addPass(new EffectPass(camera, this.bloom)) // make the whole scene super bright when it should do nothing ?
```

### Expected behavior

Threshold & intensity respected 

### Screenshots

With composer but no bloom : 
<img width="668" alt="Screenshot 2024-04-05 at 15 24 37" src="https://github.com/pmndrs/postprocessing/assets/213351/6f1ec8d3-450b-4fe4-82c2-8836a25170b0">

With bloom all set at 0 : 
<img width="666" alt="Screenshot 2024-04-05 at 15 23 42" src="https://github.com/pmndrs/postprocessing/assets/213351/4536262c-dfcc-4d15-86a6-63b7f9ea2a39">

### Library versions used

 - Three: 0.162.0
 - Post Processing: 6.35.3

### Desktop

 - OS: MacOs
 - Browser Chrome
 - Graphics hardware: m3

**Comment by vanruesc** [comment] 2024-04-05 20:39
If the bloom intensity is set to 0, there should be no visible change, so this is likely caused by something else such as a color space misconfiguration. It's hard to tell without an actual reproduction/demo of the issue.

**Comment by Makio64** [comment] 2024-04-06 06:19
it works if i do this : 
```
this.bloomPass = new EffectPass(camera, this.bloom)
this.bloomPass.encodeOutput = false
```
but I feel its unnatural I have to do so to make it works?

**Comment by vanruesc** [comment] 2024-04-06 17:00
Chances are that you're using a custom mesh material to render the background/gradient that can be seen in the screenshot. If that's the case, you're probably missing the [#include <colorspace_fragment>](https://github.com/mrdoob/three.js/blob/f21c0992f54cb309e8b1d2a5287f44c269fe1d89/src/renderers/shaders/ShaderLib/meshbasic.glsl.js#L110) snippet at the end of your shader. That means that your current render result without postprocessing is technically darker than it should be.

After fixing the conversion, you'll need to convert your input colors to linear-sRGB by using [color.convertSRGBToLinear()](https://threejs.org/docs/?q=color#api/en/math/Color.convertSRGBToLinear).

**Comment by vanruesc** [comment] 2024-04-13 23:19
Closing as resolved.

**Closed by vanruesc** 2024-04-13 23:19 UTC
Labels: support
