### ISSUE TITLE
SSAO Pass: Camera Scale affecting SSAO effect

### ISSUE THREAD

**Issue by c4b4d4** [pmndrs/postprocessing#441] opened 2022-12-24 17:02 UTC
I've found that if I change the camera scale (literally, `camera.scale.set(10,10,10));` the SSAO diminishes it's effect.

I'm using SSAO effect from https://github.com/pmndrs/postprocessing as follows:

```
const normalPass = new NormalPass(scene, camera);
const effect = new SSAOEffect(camera, normalPass.texture, {
	worldDistanceThreshold: 20,
	worldDistanceFalloff: 5,
	worldProximityThreshold: 0.4,
	worldProximityFalloff: 0.1,
	luminanceInfluence: 0.7,
	samples: 16,
	radius: 0.04,
	intensity: 1,
	resolutionScale: 0.5
});
```

Here are some images on how camera scale affects the SSAO effect. (I exaggerated intensity of SSAO so it's more clear)

When Camera Scale is `(1,1,1)`:
![Screenshot 2022-12-24 at 2.43.58|586x500, 50%](https://global.discourse-cdn.com/standard17/uploads/threejs/original/3X/c/2/c2ef08f4d641d06e8c4ed53560a4d4dc3d0be7cf.jpeg)

When Camera Scale is `(2,2,2)`:
![Screenshot 2022-12-24 at 2.45.19|612x500, 50%](https://global.discourse-cdn.com/standard17/uploads/threejs/original/3X/3/f/3f7c91327e0decb6d967d4500831fa98092ebdba.jpeg)

When Camera Scale is `(5,5,5)`:
![Screenshot 2022-12-24 at 2.45.55|618x500, 50%](https://global.discourse-cdn.com/standard17/uploads/threejs/original/3X/2/3/23e89bd6a3bdec29aeb81d40f6eb987beed361dd.jpeg)

When Camera Scale is `(10,10,10)`:
![Screenshot 2022-12-24 at 2.46.24|673x499, 50%](https://global.discourse-cdn.com/standard17/uploads/threejs/original/3X/a/2/a2321b0ad27f5162d974a0aa7cee5cff6ca279c0.jpeg)

When Camera Scale is `(20,20,20)`:
![Screenshot 2022-12-24 at 2.46.49|612x500, 50%](https://global.discourse-cdn.com/standard17/uploads/threejs/original/3X/d/2/d2328342f92c9619c708ee96e88e5a48c8b39b39.jpeg)

*(All screenshots had the same intensity value for the SSAO)*

What can I adjust on the **SSAO** effect so it's get "normalized" to whatever I set as the camera scale?

*(Note: I've had other problems before because of using a different camera scale than `(1,1,1)`, and I've solved it by just multiplying whatever's been affected by the scale of the camera. But in this case I haven't been able to figure out what parameters needs to be adjusted.)*

**Comment by vanruesc** [comment] 2022-12-25 13:29
What's the use case for changing the scale of the camera object? I didn't know this was possible / had any effect.

I've looked around and found this: https://github.com/mrdoob/three.js/issues/24800#issuecomment-1304716819
> Cameras in three.js should not have a scale applied.

If you're trying to change the scale of all objects, you could change the scale of the scene instead. The different results that you're seeing with SSAO are to be expected since the effective world size of the objects is different with each configuration. You could try multiplying `worldProximityThreshold` and `worldProximityFalloff` by the camera scale. You might also want to set `worldDistanceThreshold` to some very high value (`camera.far` multiplied by camera scale?) and `worldDistanceFalloff` to 0 to make sure SSAO never fades out.

**Comment by c4b4d4** [comment] 2022-12-25 19:50
> What's the use case for changing the scale of the camera object? I didn't know this was possible / had any effect.

I accidentally found one very good use some time ago. But I'm trying to find a workaround now to stop using this _discovered characteristic_ to avoid issues like these... might stick with it if I don't find the alternative. [**Fixing mesh overlaps in dynamic unknown scenes** (https://discourse.threejs.org/t/fixing-mesh-overlaps-in-dynamic-unknown-scenes/46194)](https://discourse.threejs.org/t/fixing-mesh-overlaps-in-dynamic-unknown-scenes/46194)

Scaling the camera basically helps **three.js** to do better calculations on the depths for meshes that are too close to each other.

Camera **scale** of `(1,1,1)` vs Camera **scale** of `(10,10,10)`
<div>
<img src="https://user-images.githubusercontent.com/375183/209479800-be6eb4d9-4d4d-4986-99a4-f10d78b33003.png" height="250">

<img src="https://user-images.githubusercontent.com/375183/209479873-857a3f80-7f94-41e7-b3ea-40d23695bd37.png" height="250">
</div>

So, scaling the scene would be more problematic, because I'll be modifying world scale, camera scale does not modify it and I don't know if it fixes these meshes overlaps. Which is guy I'm scaling the camera.

I tried multiplying `worldProximityThreshold` and `worldProximityFalloff` by the `camera.scale` but didn't work. Also have set `worldDistanceFalloff` to `0` and didn't work.

**Comment by vanruesc** [comment] 2022-12-28 23:35
This type of clipping is caused by insufficient depth precision which could mean that your dynamic scenes are too large. Have you tried limiting the size of the dynamic scenes to predefined bounds? You could scale the scene to make its bounding box match your world limits.

I don't know what changing the camera scale really does, but it looks like it affects depth precision in some way. Unfortunately, SSAO is already tricky enough to configure for common scenes so I'd also recommend not changing the camera scale if possible.

**Comment by vanruesc** [comment] 2024-02-11 23:14
Closing this as it seems to be resolved.

**Closed by vanruesc** 2024-02-11 23:14 UTC
Labels: support

**Comment by c4b4d4** [comment] 2024-02-14 04:12
> This type of clipping is caused by insufficient depth precision which could mean that your dynamic scenes are too large.

I ended up fixing the root cause of the problem, which it was having very big difference between `far` and `near` camera's props.

Which fixed all of the related issues I mentioned in this post.
