### ISSUE TITLE
background flickering on some macOS devices

### ISSUE THREAD

**Issue by MajorMeerkatThe3rd** [pmndrs/postprocessing#550] opened 2023-11-16 16:49 UTC
### Description of the bug

On some devices the background flickers as shown in the video below. It seems like this is related to the anti-aliasing effect.
This only happens on specific Apple devices as far as we know. It does happen on more than once device though.

https://github.com/pmndrs/postprocessing/assets/40572701/8e2c65ea-80ab-4e91-86b2-f2811532dd2d

### To Reproduce

[Here](https://codesandbox.io/s/ih5qh7) is the example from the video.

### Library versions used

 - Three: 0.152.0
 - Post Processing: 6.33.1

### Desktop

 - OS: macOS Sonoma 14.0
 - Browser: Chrome
 - Graphics hardware: Apple M1 Max Chip

**Comment by vanruesc** [comment] 2023-11-17 13:59
I'm unable to reproduce this locally.

If it's a driver or device bug, there's not much we can do.

**Comment by vanruesc** [comment] 2023-11-20 22:58
The flickering may also be related to the renderer's clear alpha which is set to `0.5` in the provided example. It's generally safer to use an opaque clear color for postprocessing workflows.

**Comment by MajorMeerkatThe3rd** [comment] 2023-11-21 10:45
@vanruesc Thank you for your input, unfortunate if that is something device specific as the Apple M1 Max is quite a new device.

I just updated the example and removed the alpha value, the issue still happens there.

**Comment by dghez** [comment] 2023-12-04 15:59
Currently experimenting almost the same thing but on my M1 13".
I switched from the main renderer to a composer and when I do it starts flicker the background even if I set 
`setClearColor(....solid)` and `setClearAlpha(1)`, weird.
Haven't found a solution yet

**Comment by vanruesc** [comment] 2023-12-05 20:01
Does this also occur in any of three's [postprocessing examples](https://threejs.org/examples/?q=postprocessing)?

**Comment by dghez** [comment] 2023-12-05 22:27
Oh I forgot to reply sorry, I found out the fact my issue was not related to this (but I was messing with rendertargets with `onBeforeRender`) but I can see the flicker in the demo of @MajorMeerkatThe3rd, so something is happening there.
I'm on `Brave + MacOs 14.0 on Mac 13" M1`

No flicker on the official threejs' examples

**Comment by vanruesc** [comment] 2024-02-11 22:45
I've tested this issue with a different [sandbox](https://stackblitz.com/edit/postprocessing) on macOS Sonoma with Chrome 121 and there was no flickering. This sandbox uses the latest alpha of `postprocessing` v7.

I don't know what caused the flickering in the original sandbox and tried to poke at it, but I'm am unable to modify/publish a fork of it due to CSB's pricing/plan changes so I'm closing this as a device issue.

If the flickering occurs again with a specific setup using v7, please open a new ticket.

**Closed by vanruesc** 2024-02-11 22:45 UTC
Labels: device issue, macOS

**Comment by dghez** [comment] 2024-03-10 10:49
hey there!
I'm seeing it too now. I'm on M1, Brave `[Version 1.62.153 Chromium: 121.0.6167.85 (Official Build) (arm64)](https://brave.com/latest/)`,  `MacOS Sonoma 14.3.1 (23D60)`

My deps are: 
```
"postprocessing": "^6.35.1",
"three": "^0.162.0"
```

Code: 
```js
this._composer = new EffectComposer(this._gl);
this._renderPass = new RenderPass(this._scene, this._camera);

const cae = new ChromaticAberrationEffect({
  offset: new Vector2(0.002, 0.002),
});
this._effectPass = new EffectPass(this._camera, cae);

this._composer.addPass(this._renderPass);
this._composer.addPass(this._effectPass);
```



https://github.com/pmndrs/postprocessing/assets/6367879/08220b30-013d-45cc-b50c-c17ce5d94771

**Comment by dghez** [comment] 2024-03-19 10:14
Update on my prev issue here above: using FloatType or HalfFloatType solved the issue 
```js
new EffectComposer(this._gl, {
      frameBufferType: FloatType, // prevents flicker (even with HalfFloatType)
});
```

**Comment by vanruesc** [comment] 2024-03-19 23:01
@dghez Then it's probably directly caused by hardware-based sRGB conversion for frame buffers. Postprocessing uses `UnsignedByteType` sRGB frame buffers to store intermediate results by default ([see readme](https://github.com/pmndrs/postprocessing?tab=readme-ov-file#output-color-space)).

**Comment by dghez** [comment] 2024-03-19 23:04
@vanruesc looks like is a known issue https://github.com/mrdoob/three.js/issues/24002 and they filed a bug already on https://issues.chromium.org/issues/40842482
