### ISSUE TITLE
Can't build in Angular with errors in types/postprocessing.d.ts

### ISSUE THREAD

**Issue by Zundrium** [pmndrs/postprocessing#395] opened 2022-08-03 15:14 UTC
I'm having issues with building after including the EffectComposer. 

I assume I'm doing something wrong because I haven't found any results about this. But I have no idea where to look, the error is as follows: 

In an empty Angular project I install `three`, `@types/three` and `postprocessing`.

`import {EffectComposer} from 'postprocessing'` triggers the following errors:

```
'fullscreenMaterial' is defined as an accessor in class 'Pass', but is overridden here in 'AdaptiveL
uminancePass' as an instance property.
'fullscreenMaterial' is defined as an accessor in class 'Pass', but is overridden here in 'CopyPass'
 as an instance property.
'fullscreenMaterial' is defined as an accessor in class 'Pass', but is overridden here in 'DepthCopy
Pass' as an instance property.
... and many more 
```
Does someone know where I have to look?

**Comment by Zundrium** [comment] 2022-08-04 16:55
Reverting back to version 6.25.0 (last one without type files) and declaring `postprocessing` as a module allows me to compile the project. Not really a solution though.

**Comment by vanruesc** [comment] 2022-08-04 19:09
There's has to be something wrong with your setup. Any chance you could provide a repository with a minimal reproduction of the issue?

**Comment by Zundrium** [comment] 2022-08-07 10:57
Thanks for your reply @vanruesc , it happens in an empty Angular project with the steps I mentioned above.

**Comment by Cloov** [comment] 2022-08-08 16:35
I've had the same issue, but not while using Angular. I'm using `threejs` `0.143.0`, which is currently the latest release, and I'm also using `"@types/three": "^0.143.0".

My full dependencies are as follows:

```
	"devDependencies": {
		"@types/three": "^0.136.1",
		"autoprefixer": "^10.4.0",
		"prettier": "^2.5.0",
		"sass": "^1.43.5",
		"typescript": "^4.3.2",
		"vite": "^2.6.14"
	},
	"dependencies": {
		"path": "^0.12.7",
		"three": "^0.136.0",
		"lil-gui": "^0.16.0",
		"vite-plugin-live-reload": "^2.1.0"
	}
```

**Comment by vanruesc** [comment] 2022-08-31 22:09
The types have been updated and validated in `postprocessing@6.28.7`. Please check again if the reported issue still persists.

**Comment by Cloov** [comment] 2022-09-01 16:11
Good news: no more errors for me, personally, upon updating to `postprocessing@6.28.7`. Thanks for the update!

**Comment by vanruesc** [comment] 2022-09-14 20:35
Closing this as it seems to be resolved.

**Closed by vanruesc** 2022-09-14 20:35 UTC
Labels: support
