### ISSUE TITLE
Scene blinking issue on M1 Mac when add any effect pass

### ISSUE THREAD

**Issue by Suprhimp** [pmndrs/postprocessing#428] opened 2022-11-21 02:38 UTC
Hi, again!

I met scene blinking issue only on my mac.

I checked same code with my window labtop but this symptom occurs only in my M1 mac.

I didn't checked intel mac.

https://user-images.githubusercontent.com/73486185/202951243-2324bfbc-cfdf-49d1-ba9a-861d410cbf0e.mp4

I added and check with `copypass`,`godsraypass`, `smaapass` each.

And also, I checked with codesandbox on my m1 mac. this symptom dose not occur.

**Comment by vanruesc** [comment] 2022-11-24 22:03
The blinking seems to only affect the background :thinking: Unfortunately, I don't know what could cause this.

If possible, please provide a reproduction of the issue for troubleshooting.

**Comment by Suprhimp** [comment] 2022-12-01 05:55
Thanks for answer.
I made my repository for next environment. with postprocessing

https://github.com/Suprhimp/postprocess-next-test

you can test with my repo :)

**Comment by donmccurdy** [comment] 2023-01-04 02:23
Likely related:

- https://github.com/mrdoob/three.js/issues/24002
- https://bugs.chromium.org/p/chromium/issues/detail?id=1329199&q=&can=2

**Comment by vanruesc** [comment] 2023-01-04 22:02
Thanks @donmccurdy! I'm closing this then since it appears to be an ANGLE bug.

@Suprhimp if you need this to work with broken browsers on M1 devices, try using [high precision frame buffers ](https://github.com/pmndrs/postprocessing#output-encoding) to avoid hardware sRGB encoding. Please note that this workaround may have a negative impact on performance.

**Closed by vanruesc** 2023-01-04 22:02 UTC
Labels: troubleshooting
