### ISSUE TITLE
Depth on Chrome-Mac ruined after update.

### ISSUE THREAD

**Issue by MrMateo7** [pmndrs/postprocessing#399] opened 2022-08-16 20:20 UTC
### Description of the bug

I was working with v6.26.3 and working perfectly, I update recently to the latest version v6.28.4 and noticed than in Chrome on Mac renders incrrectly. Like its buffering improperly.

### To Reproduce

Very simple code.

```
const renderPass = new RenderPass(scene, camera)

    const fxaaEffect = new FXAAEffect()
    // fxaaEffect.subpixelQuality = 0.1


    const ePass = new EffectPass( 
        camera,
        fxaaEffect,
    )

    composer = new EffectComposer(renderer, {
        frameBufferType: THREE.HalfFloatType
    })
    composer.addPass( renderPass )
    composer.addPass( ePass )
```

### Expected behavior

Render as the previous version.

### Screenshots

As it should look.
![image](https://user-images.githubusercontent.com/80969412/184976908-123ba6d1-a952-4719-a1c2-4498f41049be.png)

How currently looks.
![image](https://user-images.githubusercontent.com/80969412/184976981-af03ba79-db94-454d-9791-ca5eb612e441.png)

### Library versions used

 - Three: "^0.132.2"
 - Post Processing: "^6.28.4"

### Desktop

 - OS: Mac
 - Browser: Chrome
 - Graphics hardware: NA

**Comment by vanruesc** [comment] 2022-08-16 21:05
This looks like a strange depth buffer issue, but I don't recall any recent changes that could have caused this. Are you sure that this problem does _not_ occur with v6.26.3? Did the installed version of `three` change during the update?

**Comment by MrMateo7** [comment] 2022-08-18 16:04
I've reviewed the changelog and find this.

The first update was this one
![image](https://user-images.githubusercontent.com/80969412/185440791-e8026f90-e7b4-4065-be52-d14a4875e129.png)
After this
![image](https://user-images.githubusercontent.com/80969412/185440907-a4db85dd-3ee3-4a05-a7fa-6c9aa6985ba0.png)
Finally, this.
![image](https://user-images.githubusercontent.com/80969412/185440969-10eaf3a7-b275-448e-b622-f16b8fe312bd.png)

I'm absolutely sure than with `Three v0.133.1 and Post v6.23.1` (initial) it works fine. In one of those updates this issue appears.
Why do you think is this happening now?

**Comment by vanruesc** [comment] 2022-08-18 20:53
1. Are there any errors or warnings in the console?
1. Does this problem only occur on Mac?
1. Are you using a custom mesh material?
1. Does the issue occur when you only use a `RenderPass`? If so, does it still occur if you render the scene with `renderer.render(scene, camera);`?
1. Why did you downgrade `three` from r133 to r132? Does the issue occur with `three@0.133.1` + `postprocessing@6.28.4`?
1. Can you try updating `three` to r142 (or r143 with pp 6.28.5)?

**Comment by MrMateo7** [comment] 2022-08-25 18:19
Hi again!
Sorry for the delay, I was testing... and I found than the bug is related to the `FXAAEffect`.
![image](https://user-images.githubusercontent.com/80969412/186738532-801b524f-0001-47c3-b3b3-bfee80a43631.png)

**Comment by vanruesc** [comment] 2022-08-25 21:04
Hey, thanks for investigating. This will be hard to debug because I don't own a Mac.

Please check if this sandbox fails on your Mac: https://codesandbox.io/s/pensive-rain-jogpxy?file=/src/App.js
and if it fails, try uncommenting the lines (76, 77, 78). This replaces the FXAA shader with a simple pass-through shader. If that fixes it, try uncommenting line 80 and if it still fails, we'll need to narrow it down further.

**Comment by vanruesc** [comment] 2022-10-17 12:36
The sandbox I posted above works as expected on macOS Monterey with Chrome 106 via browserstack.

I'm closing this issue because I'm unable to reproduce it. Feel free to reopen if you have a working reproduction of the bug that can be tested on a specific system.

**Closed by vanruesc** 2022-10-17 12:36 UTC
Labels: troubleshooting, chrome, macOS
