### ISSUE TITLE
emissiveMap works unexpected with EffectPass

### ISSUE THREAD

**Issue by vivitan** [pmndrs/postprocessing#525] opened 2023-08-21 08:36 UTC
### Description of the bug

emissiveMap works unexpected with EffectPass.

### To Reproduce

sandbox :  https://codesandbox.io/s/white-snowflake-5kcy2p?file=/src/App.js

### Expected behavior
<img width="432" alt="image" src="https://github.com/pmndrs/postprocessing/assets/15190908/62e4aa73-fb9e-4dd3-8a1d-785fd5f66660">

### current behavior
<img width="480" alt="image" src="https://github.com/pmndrs/postprocessing/assets/15190908/0d594745-ae4d-4239-8e90-976f77a5e0ae">

Hope to get your help

**Comment by vanruesc** [comment] 2023-08-21 21:54
Related to #421

Transparent objects are blended differently when using post-processing.
See also https://github.com/mrdoob/three.js/issues/23019#issuecomment-1175096174

**Comment by vanruesc** [comment] 2023-08-27 11:06
Closing this as it's working as intended.

**Closed by vanruesc** 2023-08-27 11:06 UTC
Labels: support
