### ISSUE TITLE
same-scene, multi-camera rendering

### ISSUE THREAD

**Issue by xuchaozou** [pmndrs/postprocessing#507] opened 2023-06-24 03:00 UTC
### Is your feature request related to a problem?

Now we need to do the three-view function,
```
// render first view
  renderer.setViewport(0, 0, window.innerWidth / 3, window.innerHeight);
  renderer.setScissor(0, 0, window.innerWidth / 3, window.innerHeight);
  renderer.setScissorTest(true);
  renderer.render(scene, camera1);


  //  render second view
  renderer.setViewport(window.innerWidth / 3, 0, window.innerWidth / 3, window.innerHeight);
  renderer.setScissor(window.innerWidth / 3, 0, window.innerWidth / 3, window.innerHeight);
  renderer.setScissorTest(true);
  renderer.render(scene, camera2);


  //render thrid view
  renderer.setViewport((window.innerWidth / 3) * 2, 0, window.innerWidth / 3, window.innerHeight);
  renderer.setScissor((window.innerWidth / 3) * 2, 0, window.innerWidth / 3, window.innerHeight);
  renderer.setScissorTest(true);
  renderer.render(scene, camera3);
```
May I ask how the configuration can support this new requirement，
i need to you help 
thanks!!!

**Comment by vanruesc** [comment] 2023-06-24 21:51
Duplicate of #386.

Support for scissor/viewport is planned but not there yet.

**Closed by vanruesc** 2023-06-24 21:51 UTC
Labels: feature request

**Comment by xuchaozou** [comment] 2023-06-25 01:24
do you mean multiple camera
example:
```
// render first view
  renderer.setViewport(0, 0, window.innerWidth / 3, window.innerHeight);
  renderer.setScissor(0, 0, window.innerWidth / 3, window.innerHeight);
  renderer.setScissorTest(true);
  renderer.render(scene, camera1);


  //  render second view
  renderer.setViewport(window.innerWidth / 3, 0, window.innerWidth / 3, window.innerHeight);
  renderer.setScissor(window.innerWidth / 3, 0, window.innerWidth / 3, window.innerHeight);
  renderer.setScissorTest(true);
  renderer.render(scene, camera2);


  //render thrid view
  renderer.setViewport((window.innerWidth / 3) * 2, 0, window.innerWidth / 3, window.innerHeight);
  renderer.setScissor((window.innerWidth / 3) * 2, 0, window.innerWidth / 3, window.innerHeight);
  renderer.setScissorTest(true);
  renderer.render(scene, camera3);
```

**Comment by xuchaozou** [comment] 2023-06-25 01:25
i see the code , it's always only a camera

**Comment by vanruesc** [comment] 2023-06-25 23:38
Oh, have you tried using multiple `RenderPass` instances with different cameras? You can change scissor/viewport settings in-between passes with the [LambdaPass](https://pmndrs.github.io/postprocessing/public/docs/class/src/passes/LambdaPass.js~LambdaPass.html). Also make sure to disable auto clear of the render passes: `renderPass.clearPass.enabled = false`.

**Comment by xuchaozou** [comment] 2023-06-26 01:23
But I end up using EffectPass, and the first parameter of effectPass can only be the camera parameter, and I don't know how to render different parts of the same dom with multiple cameras
![image](https://github.com/pmndrs/postprocessing/assets/52873083/9520773f-96ee-499a-9778-d8ce128f6b3f)
To achieve this effect, look at a model different camera different view, their post-processing is the same

**Comment by xuchaozou** [comment] 2023-06-29 06:26
When will the v7 version be released? I urgently need this feature support, thank you
