### ISSUE TITLE
Postprocessing and MeshPhysicalMaterial transmission rendering issue in HalfFloat type

### ISSUE THREAD

**Issue by epouliquen** [pmndrs/postprocessing#431] opened 2022-11-24 17:56 UTC
### Description of the bug

Any MeshPhysicalMaterial using transmission has rendering issue when HDR image is seen in refraction : It creates "burning" artifacts.

This appears only when the effectcomposer type is in HalfFloat or Float types. But using none of these types, refraction is ok but everything else has banding.

I don't understand why this happens because reading Three js Renderers sources show that they use Halfloat type texture for refraction renderTarget...

The issue happens for any kinf of effect pass of the postprocessing lib (except RenderPass) (I've tried with saturation, SSAO, ToneMapping etc).

### To Reproduce

Please try this codesandbox to reproduce burning artifacts : https://codesandbox.io/s/halffloat-transmission-issue-2j3hr7?file=/src/index.js

### Expected behavior

No blue parts (seems segative) as you can see in under screenshot

### Screenshots

![image](https://user-images.githubusercontent.com/50987570/203844161-08d0cdb7-82ca-41e9-9247-fefd516c7909.png)

### Library versions used

 - Three: 0.146.0
 - Post Processing: 6.29.1

### Desktop

 - OS: Windows
 - Browser Chrom
 - Graphics hardware: NVIDIA

**Comment by vanruesc** [comment] 2022-11-24 21:49
Thanks for the report!

I can reproduce the issue, but I'm not sure what causes it. I'll take a closer look when I get a chance.

**Comment by vanruesc** [comment] 2023-07-17 00:39
I checked this again with the latest version of `three` and the issue seems to be gone: https://codesandbox.io/s/halffloat-transmission-issue-forked-w4zc7y

Closing this as resolved.

**Closed by vanruesc** 2023-07-17 00:39 UTC
Labels: investigating
