### ISSUE TITLE
SMAAImageLoader deprecated

### ISSUE THREAD

**Issue by Suprhimp** [pmndrs/postprocessing#424] opened 2022-11-11 09:13 UTC
Hi I'd like to ask about SMAAImageLoader deprecated

	
I think it's means i don't have to do like under this
	
	const smaaImageLoader = new SMAAImageLoader(loadingManager);

		const anisotropy = Math.min(this.composer.getRenderer()
			.capabilities.getMaxAnisotropy(), 8);

		return new Promise((resolve, reject) => {

			if(assets.size === 0) {

				loadingManager.onLoad = () => setTimeout(resolve, 250);
				loadingManager.onProgress = ProgressManager.updateProgress;
				loadingManager.onError = url => console.error(`Failed to load ${url}`);

				Sponza.load(assets, loadingManager, anisotropy);

				smaaImageLoader.load(([search, area]) => {

					assets.set("smaa-search", search);
					assets.set("smaa-area", area);

				});

			} else {

				resolve();

			}

		});
	
	
than is it enough to use like this code?
		
		    const smaaEffect = new SMAAEffect();

                    smaaEffect.edgeDetectionMaterial.edgeDetectionThreshold = 0.2;
                    
                    smaaEffect.edgeDetectionMaterial.predicationMode = PredicationMode.DEPTH;
                    
                    smaaEffect.edgeDetectionMaterial.predicationThreshold = 0.002;
                    
                    smaaEffect.edgeDetectionMaterial.predicationScale = 1.0;
                    
                    const smaaImageLoader = new SMAAImageLoader(loadingManager);
                    
                    const smaaPass = new EffectPass(camera, smaaEffect);
                    
                    composer.addPass(smaaPass);

**Comment by vanruesc** [comment] 2022-11-11 22:36
> is it enough to use like this code?

The `SMAAImageLoader` is no longer needed. See also: https://github.com/pmndrs/postprocessing/blob/64d2829f014cfec97a46bf3c109f3abc55af0715/manual/assets/js/src/demos/smaa.js#L106-L116

**Comment by Suprhimp** [comment] 2022-11-13 07:15
Thanks for reply!

I didn't know that there are other code on manual folder

is there any chance to look live demo of that manual demo?

and plus, I can't feel difference with smaa effect.. Is there any way to check the smaaEffect is really working?

**Comment by vanruesc** [comment] 2022-11-13 12:04
> is there any chance to look live demo of that manual demo?

The manual is still a work in progress and will be published together with the next major release.

>  I can't feel difference with smaa effect.. Is there any way to check the smaaEffect is really working?

If you provide a reproduction of the issue, I'll take a look.

> Also I think there is no parameter of blendFunction for type script version

The types are currently only loosely maintained. All type issue will be resolved in the next major.

**Comment by vanruesc** [comment] 2022-11-16 20:36
Closing as this seems to be resolved.

**Closed by vanruesc** 2022-11-16 20:36 UTC
Labels: question
